# Generated by Django 5.2.8 on 2025-11-14 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('morador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencial_do_dia', models.IntegerField()),
                ('data_recebimento', models.DateField(auto_now_add=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('local_armazenado', models.CharField(choices=[('estante', 'Estante'), ('chao', 'Chão'), ('outro', 'Outro local')], default='estante', max_length=50)),
                ('retirado', models.BooleanField(default=False)),
                ('data_retirada', models.DateTimeField(blank=True, null=True)),
                ('retirado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('assinatura', models.ImageField(blank=True, null=True, upload_to='assinaturas/')),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morador.morador')),
                ('recebido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
