# Generated by Django 5.2.8 on 2025-11-14 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0001_initial'),
        ('morador', '0002_apartamento_bloco_alter_morador_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='apartamento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='morador.apartamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='morador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='morador.morador'),
        ),
    ]
