# Generated by Django 5.2.8 on 2025-11-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0002_encomenda_apartamento_alter_encomenda_morador'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
