# Generated by Django 5.2.8 on 2025-11-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0003_encomenda_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='identificador_pacote',
            field=models.CharField(blank=True, help_text='Código lido do pacote (QR ou código de barras)', max_length=100, null=True),
        ),
    ]
