# Generated by Django 5.2.8 on 2025-12-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0004_encomenda_identificador_pacote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='local_armazenado',
            field=models.CharField(choices=[('estante', 'Estante'), ('chao', 'Chão'), ('carta', 'Carta'), ('outro', 'Outro local')], default='estante', max_length=50),
        ),
    ]
