# Generated by Django 5.2.8 on 2025-11-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('bloco', models.CharField(max_length=10)),
                ('apartamento', models.CharField(max_length=10)),
            ],
        ),
    ]
