# Generated by Django 5.2.8 on 2025-11-14 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['bloco__nome', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='morador',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='morador',
            name='apartamento',
        ),
        migrations.RemoveField(
            model_name='morador',
            name='bloco',
        ),
        migrations.AddField(
            model_name='morador',
            name='apartamentos',
            field=models.ManyToManyField(blank=True, related_name='moradores', to='morador.apartamento'),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='bloco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartamentos', to='morador.bloco'),
        ),
        migrations.AlterUniqueTogether(
            name='apartamento',
            unique_together={('numero', 'bloco')},
        ),
    ]
