# Generated by Django 5.2.8 on 2025-12-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morador', '0002_apartamento_bloco_alter_morador_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartamento',
            options={'ordering': ['bloco__id', 'numero']},
        ),
        migrations.AlterModelOptions(
            name='bloco',
            options={'ordering': ['id']},
        ),
    ]
